### ISSUE TITLE
请问为什么出现这种错误？

### ISSUE THREAD

**Issue by wuwenbo5** [shyandsy/cipher2#9]
flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method Encrypt_AesCbc128Padding7 on channel cipher2)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
    <asynchronous suspension>
    #1      Cipher2.encryptAesCbc128Padding7 (package:cipher2/cipher2.dart:14:20)

**Comment by shyandsy** [comment]
运行example时候会出这个错么？

flutter dcotor贴一下
android还是ios，模拟器还是真机

**Comment by wuwenbo5** [comment]
已经解决了，重启下studio就好了

**Comment by NetFly-VPN** [comment]
> 运行example时候会出这个错么？
> 
> flutter dcotor贴一下
> android还是ios，模拟器还是真机

我再华为荣耀v10 上运行 会报这个错误, 重启android studio也不行, 我这边报错:
```
MissingPluginException(No implementation found for method Decrypt_AesGcm128 on channel cipher2)
```
